site:
  title: COCONUT - Bluebook
  url: http://localhost
  start_page: component-b::index.adoc
content:
  sources:

    - url: https://github.com/mamanwhide/env-Dev.git
      branches: main
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true
output:
  dir: ./build
